name: v2xset_how2comm_stcformer_opv2v
# root_dir: '/data/v2xset/train'
# validate_dir: '/data/v2xset/validate'

root_dir: '/home/wang/code/dataset/opv2v/train'
validate_dir: '/home/wang/code/dataset/opv2v/train'

wild_setting:
  async: true #为true时开启延迟模式
  async_mode: real #real表示开启真实值随机模拟，sim表示固定延迟
  async_overhead: 600 #单位为ms
  seed: 20
  loc_err: false
  xyz_std: 0
  ryp_std: 0
  data_size: 1.06 
  transmission_speed: 27 
  backbone_delay: 0 


yaml_parser: "load_point_pillar_params"
train_params:
  batch_size: &batch_size 1
  epoches: 20
  eval_freq: 2
  save_freq: 1
  max_cav: &max_cav 5
  frame: &frame 1 # 这个参数现在可以不用了，但为了兼容性可以保留
  lsh: # Long-Short History Parameters
    m: 0 # Number of long-term frames
    n: 0 # Number of short-term frames
    p: 3 # Period for long-term frames



fusion:
  core_method: 'IntermediateFusionDataset' 
  args:
    cur_ego_pose_flag: true

preprocess:
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: &voxel_size [0.4, 0.4, 4]
    max_points_per_voxel: 32
    max_voxel_train: 32000
    max_voxel_test: 70000
  cav_lidar_range: &cav_lidar  [-140.8, -40, -3, 140.8, 40, 1]

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]


postprocess:
  core_method: 'VoxelPostprocessor' 
  gt_range: *cav_lidar
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: [0, 90]
    feature_stride: 2
    num: &achor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.20
  order: 'hwl' 
  max_num: 100 
  nms_thresh: 0.15


model:
  core_method: point_pillar_how2comm
  
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    max_cav: *max_cav
    compression: 0
    backbone_fix: false
    flow_flag: true  
    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]
    point_pillar_scatter:
      num_features: 64

    base_bev_backbone:
      resnet: True
      layer_nums: &layer_nums [3, 4, 5]
      layer_strides: [2, 2, 2]
      num_filters: &num_filters [64, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]
      compression: 0
      voxel_size: *voxel_size
    shrink_header:
      kernal_size: [ 3 ]
      stride: [ 1 ]
      padding: [ 1 ]
      dim: [ 256 ]
      input_dim: 384 

    fusion_args:
      voxel_size: *voxel_size
      downsample_rate: 1
      in_channels: 256
      n_head: 8
      dropout_rate: 0
      only_attention: true
      delay: &delay 3
      communication:
        thre: 0.01
        compressed_dim: 2
        request_flag: True
        gaussian_smooth:
          k_size: 5
          c_sigma: 1.0
        replace_mode: 'random'
        replace_ratio: 0.2
        compression: 0.5
        voxel_size: *voxel_size
        bandwidth: 50
      communication_flag: True
      agg_operator:
        mode: 'STCFormer'
        feature_dim: 256
        n_head: 8
        depth: 1
        embed_pos: None
        with_spe: false
        with_scm: false
        hetero: False
      multi_scale: true
      frame: *frame
      layer_nums: *layer_nums
      num_filters: *num_filters
      temporal_fusion:  
        height: [100, 50, 25, 100]
        width: [352, 176, 88, 352]
        layers: 1 
        channel: [64, 128, 256, 256]
        gate: False
        n_head: 5
        rte_ratio: 1
        hidden_dim: [64, 128, 256, 256]  
        delay: 0
        compressed_dim: 2  
      only_ego: False
      mgdc_bev_args:
        C_V: &C_V 10
        C_F: &C_F 64
        C_D: &C_D 16
        delay: *delay
        short_frames: 3
        long_gaps: 3
        D_hidden: 128
        delay_embedding_dim: 32
      granularity_trans:
        C_V: *C_V
        C_F: *C_F
        C_D: *C_D
        d_model: 256
        bev_h: 100
        bev_w: 352


loss:
  core_method: point_pillar_loss
  args:
    cls_weight: 1.0
    reg: 2.0

optimizer:
  core_method: Adam
  lr: 0.002
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep 
  gamma: 0.1
  step_size: [10, 20]
